### ISSUE TITLE
Plan A Prototype

### ISSUE THREAD

**Issue by pbilling** [va-big-data-genomics/data-release-portal#2]

**Comment by pbilling** [comment]
# Roadmap

- [ ] Create a basic Quarto notebook
- [ ] Upload to GitHub
- [ ] Use Cloud Build to dockerize Quarto 
- [ ] Publish website using Cloud Run

I asked the chatbot [how to do this](https://chat.openai.com/share/31b87156-9c3b-4fdb-8559-52d698331a15). It seems like a decent starting point.

**Comment by pbilling** [comment]
# Create a basic Quarto notebook

* Install Quarto locally: https://quarto.org/docs/get-started/
* Follow the Quarto [quickstart guide](https://quarto.org/docs/websites/) to create a website
* Create a project

```
quarto create project website mysite
```

* Preview website

```
quarto preview mysite
```

**Comment by pbilling** [comment]
# Dockerize and run using Cloud Run

Following this [Google tutorial](https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-python-service).

## Create a requirements.txt file
Not sure I have any requirements yet.

## Create a Dockerfile.
I'm using [this](https://github.com/analythium/quarto-docker-examples/blob/main/Dockerfile.base) as a template even though I'm not using R.

**Comment by pbilling** [comment]
# Create a basic Quarto website (debian)

## Install Quarto
```
sudo apt-get install gdebi-core
sudo gdebi --non-interactive quarto-linux-amd64.deb
```

**Comment by pbilling** [comment]
# Build a Docker image

```
docker build -t quarto-website mysite
```
